djangoVolleyballSite/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from djangoVolleyballSite import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace='main')),
    path('user/', include('users.urls', namespace='users')),
    path('rating/', include('rating.urls', namespace='rating'))
]

if settings.DEBUG:
    urlpatterns.append(path('__debug__/', include('debug_toolbar.urls')))
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import path

from main import views

app_name = 'main'

urlpatterns = [
    path('', views.MainPageView.as_view(), name='page'),
    path('new-post/', views.PostCreateView.as_view(), name='new-post'),
    path('all-posts/', views.PostListView.as_view(), name='all-post'),
    path('all-posts/<int:pk>', views.PostDetailView.as_view(),  name='post-detail'),
    path('add/', views.SubscribeButtonView.as_view(), name='subscribe'),
    path('api/v1/postlist', views.PostAPIView.as_view()),
]

users/urls.py
from django.urls import path

from users import views

app_name = 'users'

urlpatterns = [
    path('', views.logout_user, name='logout'),
    path('registration/', views.RegistrationUserView.as_view(), name='registration'),
    path('login/', views.AuthUserView.as_view(), name='login'),
    path('profile/<int:pk>', views.ProfileUserView.as_view(), name='profile'),
    path('sendemail/<str:email>', views.SendEmailVerificationView.as_view(), name='send-email'),
    path('verify/<str:email>/<uuid:code>', views.EmailVerificationView.as_view(), name='email-verification'),
]

users/models.py
from django.core.mail import send_mail
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.urls import reverse


from rating.models import Teams


class User(AbstractUser):

    POSITION_TYPES = (
        ('S', 'Связующий'),
        ('MB', 'Центральный блокирующий'),
        ('Li', 'Либеро'),
        ('WS', 'Доигровщик'),
        ('D', 'Диагональный'),
        ('PL', 'Игрок')
    )

    image = models.ImageField('Личное фото', upload_to='user_images', blank=True, null=True)
    team = models.ForeignKey(
        Teams,
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        verbose_name='Название команды'
    )
    position = models.CharField('Позиция', max_length=25, choices=POSITION_TYPES, default='PL', blank=True)
    is_verified = models.BooleanField(default=False)

    class Meta:
        verbose_name = 'Пользователь'
        verbose_name_plural = 'Пользователи'


class EmailVerification(models.Model):
    code = models.UUIDField(unique=True)
    user = models.ForeignKey(to=User, on_delete=models.CASCADE)
    expiration = models.DateTimeField()
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name = 'Пользовательская верификация'
        verbose_name_plural = 'Пользовательские верификации'

    def __str__(self):
        return f'Код верификации для {self.user.username}'

    def send_verification_email(self):
        link = reverse('users:email-verification', kwargs={'email': self.user.email, 'code': self.code})
        verification_link = f'http://127.0.0.1:8000{link}'
        subject = f'Подтверждение учетной записи для {self.user.username}'
        message = 'Для подтверждения учетной записи {} перейдите по ссылке: {}'\
            .format(self.user.username, verification_link)
        send_mail(
            subject=subject,
            message=message,
            from_email='from@example.com',
            recipient_list=[self.user.email],
        )

templates/user_templates/emailverification.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    {% block content %}
        <h1>All Done!</h1>
    {% endblock %}

</body>
</html>

templates/user_templates/login.html
{#{% extends 'base.html' %}#}
{% block content %}
    <form method="post">
        {% csrf_token %}
        <p>
            {{ form.username}}<br>
            {{ form.password}}
        </p>
        <button type="submit">Авторизоваться</button>
    </form>
{% endblock %}

templates/user_templates/profile.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{ request.user.username }}</title>
</head>
<body>
    <img src="
        {% if player.image %}
            {{ player.image.url }}
        {% else %}
            {% static 'img/default_static/user_avatar.png' %}
        {% endif %}"
         width="100" height="100" alt="#">

    <p>Имя пользователя: {{ player.username }}<br>
    Команда: {% if player.team__name %}{{ player.team__name }} | Рейтинг команды: {{ player.team__rating }}
    {% else %}Отсутствует {% endif %}<br>
    Позиция: {{ player.get_position_display }}
    {% if player.is_verified == False and player.email != '' %}
        <a href="{% url 'users:send-email' player.email %}">Подтвердить почту!</a>
    {% endif %}</p>
    <p><a href="{% url 'main:page' %}"><-- На главную</a></p>
</body>
</html>

templates/user_templates/registration.html
{#{% extends 'base.html' %}#}
{% block content %}
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Создать</button>
    </form>
{% endblock %}

templates/user_templates/sendemail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <h1>{{ answer }}</h1>
</body>
</html>