djangoVolleyballSite/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from djangoVolleyballSite import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace='main')),
    path('user/', include('users.urls', namespace='users')),
    path('rating/', include('rating.urls', namespace='rating'))
]

if settings.DEBUG:
    urlpatterns.append(path('__debug__/', include('debug_toolbar.urls')))
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import path

from main import views

app_name = 'main'

urlpatterns = [
    path('', views.MainPageView.as_view(), name='page'),
    path('new-post/', views.PostCreateView.as_view(), name='new-post'),
    path('all-posts/', views.PostListView.as_view(), name='all-post'),
    path('all-posts/<int:pk>', views.PostDetailView.as_view(),  name='post-detail'),
    path('add/', views.SubscribeButtonView.as_view(), name='subscribe'),
    path('api/v1/postlist', views.PostAPIView.as_view()),
]

users/urls.py
from django.urls import path

from users import views

app_name = 'users'

urlpatterns = [
    path('', views.logout_user, name='logout'),
    path('registration/', views.RegistrationUserView.as_view(), name='registration'),
    path('login/', views.AuthUserView.as_view(), name='login'),
    path('profile/<int:pk>', views.ProfileUserView.as_view(), name='profile'),
    path('sendemail/<str:email>', views.SendEmailVerificationView.as_view(), name='send-email'),
    path('verify/<str:email>/<uuid:code>', views.EmailVerificationView.as_view(), name='email-verification'),
]

templates/post_templates/add_subscribe.html
<form action="{% url 'main:subscribe' %}" method="post">
    {% csrf_token %}
    <input type="hidden" name="post_pk" value="{{ post.pk }}">
    <input type="hidden" name="user_id" value="{% if request.user.is_authenticated %}{{ request.user.id }}{% else %}None{% endif %}">

    <button type="submit">Записаться</button>
</form>

templates/post_templates/all_posts.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    {% for post in posts %}
        <h1>{{ post.date_time_start|date:'l' }} ({{ post.date_time_start|date:'d.m.y' }})</h1>
        <h4>{{ post.date_time_start|date:'H:i' }} - {{ post.date_time_end|date:'H:i' }}</h4>
        <h4>Категория: <u>{{ post.category__rank }}</u></h4>
        <h6>{{ post.description|safe }}</h6>
        <h5>На игру доступно: <b>{{ post.reservation }} мест/а</b></h5>
        {% if request.user.is_authenticated %}
            {% include 'post_templates/add_subscribe.html' %}
            <a href="{% url 'main:post-detail' post.pk %}"><button type="button">Детали</button></a>
        {% else %}
            <a href="{% url 'users:login' %}"><button>Авторизоваться</button></a><
        {% endif %}
        <hr>
    {% endfor %}
{% endblock %}

templates/post_templates/new_post.html
{% extends 'base.html' %}


{% block content %}
    <form method="post">
        {% csrf_token %}
        <p>День недели: {{ form.title }}</p>
        <p>Дата проведения: {{ form.date }}</p>
        <p>Дата начала мероприятия: {{ form.time_start }}</p>
        <p>Дата окончания мероприятия: {{ form.time_end }}</p>
        <p>Описание: {{ form.description }}</p>
        <p>Категория: {{ form.category}}</p>
        <p>Количество свободных мест: {{ form.reservation }}</p>
        <p>На главную страницу? {{ form.on_main }}</p>
        <button type="submit">Создать</button>
    </form>
    {% if form.errors %}
      <ul>
        {% for key,value in form.errors.items %}
          <li>{{ key|escape }} : {{ value|escape }}</li>
        {% endfor %}
      </ul>
    {% endif %}
{% endblock %}

templates/post_templates/post_detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{ title }}</title>
</head>
<body>
    {% block content %}
        <h1>{{ post.date_time_start|date:'l' }} ({{ post.date_time_start|date:'d.m.y' }})</h1>
        <h3>{{ post.date_time_start|date:'H:i' }} - {{ post.date_time_end|date:'H:i' }}</h3>
        <h3>Категория: <u>{{ post.category__rank }}</u></h3>
        <h3>{{ post.description|safe }}</h3>
        <h5>На игру доступно: <b>{{ post.reservation }} мест/а</b></h5>
        <p>На игру записались: {{ players_today }}
        </p>
    {% endblock %}
</body>
</html>